#!/bin/bash
. tap.sh
nok true
echo $?
nok true foo
echo $?
nok <<EOCMD
true
EOCMD
echo $?
nok <<EOCMD foo
true
EOCMD
echo $?
nok false
echo $?
nok false foo
echo $?
nok <<EOCMD
false
EOCMD
echo $?
nok <<EOCMD foo
false
EOCMD
echo $?
nok <<EOCMD bar
for f in hello world!; do
    echo [\$f]
done
EOCMD
echo $?
echo "$GOT"

