#!/bin/bash
. t/test.sh
tap_is $'run true
echo $?
run false
echo $?
run <<EOCMD
true
EOCMD
echo $?
run <<EOCMD
false
EOCMD
echo $?
run "echo Tommen"
echo $GOT
run "echo Boots" FOO
echo $FOO' $'0
1
0
0
Tommen
Boots'

