#!/bin/bash
. tap.sh
val_ok 0
val_ok 0 "foo"
val_ok <<EOVALUE 0
hello world
EOVALUE
val_ok 1
val_ok 1 "foo"
val_ok 2
val_ok 255
val_ok 256
val_ok 257
val_ok 1000000
val_ok 1000000000000
val_ok
val_ok ""
val_ok "" "foo"
val_ok "this is a string with spaces"
val_ok <<EOVALUE
hello world
foo bar baz
EOVALUE
val_ok <<EOVALUE "foo"
hello world
foo bar baz
EOVALUE
